---
version: '2.0'
services:
  stackup:
    image: realestate/stackup:latest
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/build"
    working_dir: /build
    environment:
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
      - http_proxy
      - https_proxy
      - no_proxy

  python:
    image: jpbarto/boto3:latest
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/build"
    working_dir: /build
    environment:
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - FUNCTION_ARN
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
      - http_proxy
      - https_proxy
      - no_proxy

  yamllint:
    image: boiyaa/yamllint:latest
    volumes:
      - ".:/workdir"
    working_dir: /workdir

  awscli:
    image: xueshanf/awscli:latest
    volumes:
      - ".:/build"
      - "$HOME/.aws:/root/.aws"
    working_dir: /build
    environment:
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
      - http_proxy
      - https_proxy
      - no_proxy

  shellcheck:
    image: koalaman/shellcheck-alpine:latest
    volumes:
      - ".:/build"
    working_dir: /build
