TEST_TARGETS := test-lint-yaml test-validate-cfn test-validate-shell

.PHONY: test $(TEST_TARGETS)

all-test: $(TEST_TARGETS)

test-lint-yaml:
	@echo "--- Test Lint YAML"
	@docker-compose run --rm yamllint .

test-validate-cfn:
	@echo "--- Test Validate CloudFormation"
	@docker-compose run --rm awscli scripts/validate_cloudformation.sh

test-validate-shell:
	@echo "--- Test Validate Shell Scripts"
	@docker-compose run --rm shellcheck scripts/validate_shell_scripts.sh